---
hosts::parameter_one: "PRODUCTION value for parameter one"

files::file_from_templates:
  etc_apt_preferences.d_00-puppet.pref:
    target: '/etc/apt/preferences.d/00-puppet.pref'
    template: 'etc_apt_preferences.d_00-puppet.pref'
